cmake -GNinja -S llvm -B build \
 -DCMAKE_BUILD_TYPE=Debug \
 -DLLVM_ENABLE_ASSERTIONS=ON \
 -DLLVM_TARGETS_TO_BUILD="host;AMDGPU" \
 -DLLVM_ENABLE_PROJECTS="clang" \
 -DLLVM_CCACHE_BUILD=ON \
 -DCMAKE_LINKER=/opt/homebrew/bin/mold
